### PR TITLE
Allow Tappd That to open Untappd beer URLs

### PR DESCRIPTION
**Pull request by gfiumara**

### CODE REVIEW

**Comment by tijoinc** [comment]
Sweet! LGTM!

**Comment by tijoinc** [comment]
Hmm, I think I'll rename this to "Check in with beer", @gfiumara you cool with that?

**Comment by tijoinc** [comment]
Since your app is more of a journal and this action jumps to the check in screen.

**Comment by gfiumara** [comment]
Makes sense to me.

**Pull request merged**
