### PR TITLE
Added Tappd support.

### PR DESCRIPTION
**Pull request by frenchesco**
Added the ability to open app store links in Tappd.

### CODE REVIEW

**Comment by tijoinc** [comment]
Nice! You'll be the first person other than me to contribute!

Left a little bit of feedback, please check it out. I can also help if you need.

**Comment by frenchesco** [comment]
Thanks. I've added support for iTunes URLs. If you need to modify anything I created this Fiddle for testing and generating the code as I didn't know how else to test it: http://jsfiddle.net/gbjtfxwr/4/

**Comment by tijoinc** [comment]
Wow, nice!

**Comment by frenchesco** [comment]
I fixed a bug in the URL scheme. I was using `?` instead of `=`. I've also removed the new line character from the end of the file. The GitHub editor was determined to add it back in even after deleting it.

Also, I've updated [the Fiddle](http://jsfiddle.net/marcgordon/ndn4k6s3/3/) to include the ability to add `platform` and use `format` instead of `script` in the generated output. I've also added the ability to specify expectedTestResults and some additional error checking.

**Comment by tijoinc** [comment]
I'll look into merging this tonight, thanks!

**Comment by frenchesco** [comment]
Ah, I didn't realise Opener would automatically lengthen short URLs. That definitely simplifies things a lot. I've updated the code to use `format` instead of `script` and fixed the casing of `appIdentifier`.

**Comment by tijoinc** [comment]
Sweet, merged!

**Pull request merged**
